package bleephub

import (
	"fmt"
	"net/http"
	"sort"
	"strings"
)

func (s *Server) registerGHTemplateRoutes() {
	s.route("GET /api/v3/gitignore/templates", s.handleListGitignoreTemplates)
	s.route("GET /api/v3/gitignore/templates/{name}", s.handleGetGitignoreTemplate)
	s.route("GET /api/v3/licenses", s.handleListLicenses)
	s.route("GET /api/v3/licenses/{license}", s.handleGetLicense)
}

func (s *Server) handleListGitignoreTemplates(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, http.StatusOK, listGitignoreNames())
}

func (s *Server) handleGetGitignoreTemplate(w http.ResponseWriter, r *http.Request) {
	name := r.PathValue("name")
	canonical, ok := normalizeGitignoreName(name)
	if !ok {
		writeGHError(w, http.StatusNotFound, "Not Found")
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"name":   canonical,
		"source": gitignoreTemplates[canonical],
	})
}

func (s *Server) handleListLicenses(w http.ResponseWriter, r *http.Request) {
	keys := listLicenseKeys()
	out := make([]map[string]interface{}, 0, len(keys))
	for _, k := range keys {
		tmpl := licenseTemplates[k]
		out = append(out, map[string]interface{}{
			"key":     k,
			"name":    tmpl.Name,
			"spdx_id": tmpl.SpdxID,
			"url":     s.baseURL(r) + "/api/v3/licenses/" + k,
			"node_id": tmpl.NodeID,
		})
	}
	writeJSON(w, http.StatusOK, paginateAndLink(w, r, out))
}

func (s *Server) handleGetLicense(w http.ResponseWriter, r *http.Request) {
	key := strings.ToLower(r.PathValue("license"))
	tmpl, ok := licenseTemplates[key]
	if !ok {
		writeGHError(w, http.StatusNotFound, "Not Found")
		return
	}
	writeJSON(w, http.StatusOK, map[string]interface{}{
		"key":            key,
		"name":           tmpl.Name,
		"spdx_id":        tmpl.SpdxID,
		"body":           tmpl.Body,
		"description":    tmpl.Name,
		"implementation": "",
		"permissions":    []string{},
		"conditions":     []string{},
		"limitations":    []string{},
		"featured":       true,
		"html_url":       "https://choosealicense.com/licenses/" + key + "/",
		"node_id":        tmpl.NodeID,
		"url":            s.baseURL(r) + "/api/v3/licenses/" + key,
	})
}

// gitignoreTemplates is a curated list of common .gitignore templates
// matching the names GitHub serves from https://github.com/github/gitignore.
// The content is real, recognizable template text.
var gitignoreTemplates = map[string]string{
	"Go": `# Binaries for programs and plugins
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary, built with go test -c
*.test

# Output of the go coverage tool, specifically when used with LiteIDE
*.out

# Dependency directories (remove the comment below to include it)
# vendor/

# Go workspace file
go.work
`,
	"Node": `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Coverage directory used by tools like istanbul
coverage/

# Dependency directories
node_modules/

# TypeScript cache
*.tsbuildinfo
`,
	"Python": `# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# C extensions
*.so

# Distribution / packaging
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
.env
.venv
env/
venv/
`,
	"Java": `# Compiled class file
*.class

# Log file
*.log

# BlueJ files
*.ctxt

# Mobile Tools for Java (J2ME)
.mtj.tmp/

# Package Files #
*.jar
*.war
*.nar
*.ear
*.zip
*.tar.gz
*.rar

# virtual machine crash logs
hs_err_pid*
replay_pid*
`,
	"Ruby": `*.gem
*.rbc
/.config
/coverage/
/InstalledFiles
/pkg/
/spec/reports/
/spec/examples.txt
/test/tmp/
/test/version_tmp/
/tmp/

# Used by dotenv library to load environment variables.
.env

## Specific to RubyMotion:
.dat*
.repl_history
build/
*.bridgesupport
build-iPhoneOS/
build-iPhoneSimulator/
`,
	"Rust": `# Generated by Cargo
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk
`,
	"VisualStudio": `## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.rsuser
*.suo
*.user
*.userosscache
*.sln.docstates

# User-specific files (MonoDevelop/Xamarin Studio)
*.userprefs

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
[Ww][Ii][Nn]32/
[Aa][Rr][Mm]/
[Aa][Rr][Mm]64/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/
`,
}

func listGitignoreNames() []string {
	names := make([]string, 0, len(gitignoreTemplates))
	for name := range gitignoreTemplates {
		names = append(names, name)
	}
	return names
}

func listLicenseKeys() []string {
	keys := make([]string, 0, len(licenseTemplates))
	for k := range licenseTemplates {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func normalizeLicenseKey(key string) (string, bool) {
	lower := strings.ToLower(key)
	if _, ok := licenseTemplates[lower]; ok {
		return lower, true
	}
	return "", false
}

func normalizeGitignoreName(name string) (string, bool) {
	for k := range gitignoreTemplates {
		if strings.EqualFold(k, name) {
			return k, true
		}
	}
	return "", false
}

func licenseBody(key, owner, repo string, year int) string {
	tmpl := licenseTemplates[key]
	body := strings.ReplaceAll(tmpl.Body, "[year]", fmt.Sprintf("%d", year))
	body = strings.ReplaceAll(body, "[fullname]", owner)
	return body
}
