output "service_arn" { value = aws_ecs_service.this.id }
output "service_url" { value = "https://${var.domain_name}" }
output "admin_url" { value = "https://admin.${var.domain_name}" }
output "ssh_host" { value = "ssh.${var.domain_name}" }
output "service_discovery_namespace" { value = aws_service_discovery_private_dns_namespace.this.name }
output "git_bucket_name" { value = aws_s3_bucket.git.bucket }
output "object_bucket_name" { value = aws_s3_bucket.objects.bucket }
output "startup_bucket_name" { value = aws_s3_bucket.startup.bucket }
output "admin_token_secret_arn" { value = aws_secretsmanager_secret.admin_token.arn }
output "efs_access_point_id" { value = aws_efs_access_point.sqlite.id }
output "s3_gateway_endpoint_id" { value = try(aws_vpc_endpoint.s3[0].id, null) }
output "vpc_id" { value = local.vpc_id }
output "api_gateway_id" { value = aws_apigatewayv2_api.this.id }
output "api_gateway_vpc_link_id" { value = local.api_gateway_vpc_link_id }
output "api_gateway_vpc_link_security_group_id" { value = local.api_gateway_vpc_link_security_group_id }
