// Command graphqlschemagen generates internal/graphqlschema's type
// definitions from the vendored GitHub public GraphQL schema
// (third_party/github-graphql-schema.graphql.gz).
//
// bleephub hand-writes ~306 of GitHub's 1,807 GraphQL types. The remaining
// 1,500 cannot be typed by hand at the fidelity the API contract needs, so
// they are generated from the same pinned SDL the schema ratchet in
// internal/server diffs against — the generator and the oracle read one
// file, which is what makes "zero missing types, zero missing fields" a
// verifiable claim rather than an assertion.
//
// The emitted Go reproduces, per type: field names, argument names,
// argument types, default values, nullability, list nesting, @deprecated
// reasons, enum values (deprecated ones included), interface
// implementations, union members, input-object fields and descriptions.
// Every field, interface and union-member list is emitted behind a thunk
// so the schema's dense cycles (Repository → Issue → User → Repository)
// need no definition order.
//
// Run it from the repository root:
//
//	go run ./internal/graphqlschemagen
//
// or through scripts/gen-graphql-schema.sh.
package main

import (
	"bytes"
	"compress/gzip"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/parser"
	"github.com/graphql-go/graphql/language/source"
)

const (
	// defaultSchemaPath and defaultOutputDir are repository-root-relative;
	// the generator is a build-time command run from the module root.
	defaultSchemaPath = "third_party/github-graphql-schema.graphql.gz"
	defaultOutputDir  = "internal/graphqlschema"
	// generatedPackage is the package the emitted files belong to.
	generatedPackage = "graphqlschema"
	// typesPerShard keeps each emitted file reviewable and keeps the Go
	// compiler off a single multi-hundred-thousand-line source file.
	typesPerShard = 128
	// generatedHeader marks the output for `go vet`, gofmt tooling, and
	// scripts/dupl.sh (which excludes *_gen.go).
	generatedHeader = "// Code generated by internal/graphqlschemagen. DO NOT EDIT."
)

// buildPathPattern restricts operator-supplied build paths to an explicit
// safe alphabet; combined with the "no .." check it forbids
// parent-directory traversal in the schema and output paths. Mirrors
// internal/emojigen's localBuildPath.
var buildPathPattern = regexp.MustCompile(`^/?[A-Za-z0-9._/-]+$`)

func localBuildPath(p string) string {
	if p == "" || strings.Contains(p, "..") || !buildPathPattern.MatchString(p) {
		log.Fatalf("path %q is not an allowed build path", p)
	}
	resolved, err := filepath.Abs(p)
	if err != nil {
		log.Fatalf("resolve path %q: %v", p, err)
	}
	return filepath.Clean(resolved)
}

func main() {
	schemaPath := flag.String("schema", defaultSchemaPath, "path to the gzipped GitHub public GraphQL schema")
	outputDir := flag.String("out", defaultOutputDir, "directory to write the generated package files into")
	flag.Parse()

	body, err := readSchema(localBuildPath(*schemaPath))
	if err != nil {
		log.Fatalf("read schema: %v", err)
	}
	normalized, rewrites := normalizeSDL(body)
	log.Printf("normalized SDL: %d leading-pipe unions, %d explicit null defaults",
		rewrites.leadingPipes, rewrites.nullDefaults)

	document, err := parser.Parse(parser.ParseParams{
		Source: source.NewSource(&source.Source{Body: normalized, Name: *schemaPath}),
	})
	if err != nil {
		log.Fatalf("parse schema: %v", err)
	}

	definitions, err := collect(document)
	if err != nil {
		log.Fatalf("collect definitions: %v", err)
	}
	files, stats, err := emit(definitions)
	if err != nil {
		log.Fatalf("emit: %v", err)
	}
	dir := localBuildPath(*outputDir)
	if err := writeGenerated(dir, files); err != nil {
		log.Fatalf("write: %v", err)
	}
	log.Printf("wrote %d files to %s: %d types (%d objects, %d interfaces, %d unions, %d enums, %d inputs, %d scalars), %d output fields, %d input fields, %d arguments, %d lines",
		len(files), *outputDir, stats.types, stats.objects, stats.interfaces, stats.unions,
		stats.enums, stats.inputs, stats.scalars, stats.outputFields, stats.inputFields,
		stats.arguments, stats.lines)
}

func readSchema(path string) ([]byte, error) {
	// #nosec G304 -- path is validated by localBuildPath and supplied by
	// the build operator, never by a request.
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()
	reader, err := gzip.NewReader(file)
	if err != nil {
		return nil, err
	}
	defer func() { _ = reader.Close() }()
	return io.ReadAll(reader)
}

// SDL normalization

type rewriteCounts struct {
	leadingPipes int
	nullDefaults int
}

// normalizeSDL rewrites the two SDL spellings graphql-go v0.8.1's parser
// predates:
//
//   - the optional leading "|" GitHub's formatter emits before the first
//     member of a multi-line union; and
//   - "= null" argument defaults, which need the NullValue AST node the
//     vendored parser version does not have.
//
// Both rewrites are applied only outside string and comment tokens. The
// blunt regular-expression form used by the schema ratchet would also edit
// description text that happens to contain those byte sequences, and this
// generator copies descriptions into the output verbatim, so it cannot
// afford that.
//
// Dropping an explicit "= null" default is lossless for the emitted
// schema: graphql-go models "no default" as a nil DefaultValue and has no
// way to distinguish it from a default that is null.
func normalizeSDL(body []byte) ([]byte, rewriteCounts) {
	out := make([]byte, 0, len(body))
	var counts rewriteCounts
	for i := 0; i < len(body); {
		switch {
		case bytes.HasPrefix(body[i:], []byte(`"""`)):
			end := bytes.Index(body[i+3:], []byte(`"""`))
			if end < 0 {
				out = append(out, body[i:]...)
				i = len(body)
				continue
			}
			out = append(out, body[i:i+3+end+3]...)
			i += 3 + end + 3
		case body[i] == '"':
			j := i + 1
			for j < len(body) && body[j] != '"' {
				if body[j] == '\\' {
					j++
				}
				j++
			}
			if j < len(body) {
				j++
			}
			out = append(out, body[i:j]...)
			i = j
		case body[i] == '#':
			j := i
			for j < len(body) && body[j] != '\n' {
				j++
			}
			out = append(out, body[i:j]...)
			i = j
		case body[i] == '=':
			if skip, ok := matchNullDefault(body, i); ok {
				counts.nullDefaults++
				out = trimTrailingSpace(out)
				i = skip
				continue
			}
			if skip, ok := matchLeadingPipe(body, i); ok {
				counts.leadingPipes++
				out = append(out, '=', ' ')
				i = skip
				continue
			}
			out = append(out, '=')
			i++
		default:
			out = append(out, body[i])
			i++
		}
	}
	return out, counts
}

// matchNullDefault reports whether body[at] starts an "= null" default and
// returns the index just past it.
func matchNullDefault(body []byte, at int) (int, bool) {
	j := at + 1
	for j < len(body) && (body[j] == ' ' || body[j] == '\t') {
		j++
	}
	if !bytes.HasPrefix(body[j:], []byte("null")) {
		return 0, false
	}
	j += len("null")
	if j < len(body) && isNameByte(body[j]) {
		return 0, false
	}
	return j, true
}

// matchLeadingPipe reports whether body[at] starts a union assignment
// whose first member is preceded by a newline and a "|", and returns the
// index just past that pipe.
func matchLeadingPipe(body []byte, at int) (int, bool) {
	j := at + 1
	sawNewline := false
	for j < len(body) && isSpaceByte(body[j]) {
		if body[j] == '\n' {
			sawNewline = true
		}
		j++
	}
	if !sawNewline || j >= len(body) || body[j] != '|' {
		return 0, false
	}
	return j + 1, true
}

func isSpaceByte(b byte) bool {
	return b == ' ' || b == '\t' || b == '\n' || b == '\r'
}

func isNameByte(b byte) bool {
	return b == '_' || (b >= '0' && b <= '9') || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}

func trimTrailingSpace(out []byte) []byte {
	for len(out) > 0 && (out[len(out)-1] == ' ' || out[len(out)-1] == '\t') {
		out = out[:len(out)-1]
	}
	return out
}

// definition model

type definition struct {
	name string
	kind string
	node ast.Node
}

type stats struct {
	types        int
	objects      int
	interfaces   int
	unions       int
	enums        int
	inputs       int
	scalars      int
	abstracts    int
	outputFields int
	inputFields  int
	arguments    int
	lines        int
}

func collect(document *ast.Document) ([]definition, error) {
	var definitions []definition
	seen := map[string]string{}
	for _, node := range document.Definitions {
		var name, kind string
		switch typed := node.(type) {
		case *ast.ObjectDefinition:
			name, kind = typed.Name.Value, "object"
		case *ast.InterfaceDefinition:
			name, kind = typed.Name.Value, "interface"
		case *ast.UnionDefinition:
			name, kind = typed.Name.Value, "union"
		case *ast.EnumDefinition:
			name, kind = typed.Name.Value, "enum"
		case *ast.InputObjectDefinition:
			name, kind = typed.Name.Value, "input"
		case *ast.ScalarDefinition:
			name, kind = typed.Name.Value, "scalar"
		case *ast.DirectiveDefinition:
			// graphql-go has no way to attach a directive definition's
			// applications to types or fields, and GitHub's own
			// introspection does not expose applied directives either, so
			// directive definitions are intentionally not emitted. The
			// three GitHub declares (@preview, @possibleTypes,
			// @docsCategory) are documentation-only.
			continue
		default:
			return nil, fmt.Errorf("unsupported top-level definition %T", node)
		}
		if previous, duplicate := seen[name]; duplicate {
			return nil, fmt.Errorf("duplicate type name %q (%s and %s)", name, previous, kind)
		}
		seen[name] = kind
		definitions = append(definitions, definition{name: name, kind: kind, node: node})
	}
	sort.Slice(definitions, func(i, j int) bool { return definitions[i].name < definitions[j].name })
	for _, item := range definitions {
		if method := methodName(item.name); method == "defineAllTypes" {
			return nil, fmt.Errorf("type %q collides with the generated aggregator method", item.name)
		}
	}
	if _, ok := seen["Query"]; !ok {
		return nil, fmt.Errorf("schema defines no Query type")
	}
	return definitions, nil
}

func methodName(typeName string) string { return "define" + typeName }

// emission

func emit(definitions []definition) (map[string][]byte, stats, error) {
	var total stats
	shards := map[int]*bytes.Buffer{}
	var calls bytes.Buffer
	for index, item := range definitions {
		shard := index / typesPerShard
		buffer := shards[shard]
		if buffer == nil {
			buffer = &bytes.Buffer{}
			shards[shard] = buffer
			writeFileHeader(buffer, true)
		}
		if err := emitDefinition(buffer, item, &total); err != nil {
			return nil, total, err
		}
		fmt.Fprintf(&calls, "\tr.%s()\n", methodName(item.name))
		total.types++
	}
	total.abstracts = total.interfaces + total.unions

	files := make(map[string][]byte, len(shards)+1)
	for shard, buffer := range shards {
		name := fmt.Sprintf("types_%02d_gen.go", shard)
		formatted, err := format.Source(buffer.Bytes())
		if err != nil {
			return nil, total, fmt.Errorf("gofmt %s: %w", name, err)
		}
		files[name] = formatted
		total.lines += bytes.Count(formatted, []byte("\n"))
	}

	var registry bytes.Buffer
	writeFileHeader(&registry, false)
	fmt.Fprintf(&registry, `
// Counts of the generated type universe, used to presize the registry's
// maps and asserted by the completeness ratchet.
const (
	generatedTypeCount      = %d
	generatedObjectCount    = %d
	generatedInterfaceCount = %d
	generatedUnionCount     = %d
	generatedEnumCount      = %d
	generatedInputCount     = %d
	generatedScalarCount    = %d
	generatedAbstractCount  = %d
)

// defineAllTypes registers every named type's shell. Fields, interface
// lists and union members are deferred thunks, so the order here is
// irrelevant to correctness and is simply the SDL's type names sorted.
func (r *Registry) defineAllTypes() {
%s}
`, total.types, total.objects, total.interfaces, total.unions, total.enums,
		total.inputs, total.scalars, total.abstracts, calls.String())
	formatted, err := format.Source(registry.Bytes())
	if err != nil {
		return nil, total, fmt.Errorf("gofmt registry_gen.go: %w", err)
	}
	files["registry_gen.go"] = formatted
	total.lines += bytes.Count(formatted, []byte("\n"))
	return files, total, nil
}

func writeFileHeader(buffer *bytes.Buffer, withGraphQLImport bool) {
	buffer.WriteString(generatedHeader)
	buffer.WriteString("\n// Source: third_party/github-graphql-schema.graphql.gz\n\n")
	fmt.Fprintf(buffer, "package %s\n", generatedPackage)
	if withGraphQLImport {
		buffer.WriteString("\nimport \"github.com/graphql-go/graphql\"\n")
	}
}

func emitDefinition(buffer *bytes.Buffer, item definition, total *stats) error {
	switch node := item.node.(type) {
	case *ast.ObjectDefinition:
		total.objects++
		emitObject(buffer, node, total)
	case *ast.InterfaceDefinition:
		total.interfaces++
		emitInterface(buffer, node, total)
	case *ast.UnionDefinition:
		total.unions++
		emitUnion(buffer, node)
	case *ast.EnumDefinition:
		total.enums++
		emitEnum(buffer, node)
	case *ast.InputObjectDefinition:
		total.inputs++
		emitInput(buffer, node, total)
	case *ast.ScalarDefinition:
		total.scalars++
		emitScalar(buffer, node)
	default:
		return fmt.Errorf("unsupported definition %T", item.node)
	}
	return nil
}

func emitObject(buffer *bytes.Buffer, node *ast.ObjectDefinition, total *stats) {
	name := node.Name.Value
	fmt.Fprintf(buffer, "\nfunc (r *Registry) %s() {\n\tr.object(%s, %s, %s, func() graphql.Fields {\n\t\treturn graphql.Fields{\n",
		methodName(name), quote(name), describe(node.Description), interfaceList(node.Interfaces))
	emitFields(buffer, node.Fields, total)
	buffer.WriteString("\t\t}\n\t})\n}\n")
}

func emitInterface(buffer *bytes.Buffer, node *ast.InterfaceDefinition, total *stats) {
	name := node.Name.Value
	fmt.Fprintf(buffer, "\nfunc (r *Registry) %s() {\n\tr.interfaceType(%s, %s, func() graphql.Fields {\n\t\treturn graphql.Fields{\n",
		methodName(name), quote(name), describe(node.Description))
	emitFields(buffer, node.Fields, total)
	buffer.WriteString("\t\t}\n\t})\n}\n")
}

func emitFields(buffer *bytes.Buffer, fields []*ast.FieldDefinition, total *stats) {
	sorted := make([]*ast.FieldDefinition, len(fields))
	copy(sorted, fields)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name.Value < sorted[j].Name.Value })
	for _, field := range sorted {
		total.outputFields++
		fmt.Fprintf(buffer, "\t\t\t%s: {\n\t\t\t\tType: %s,\n", quote(field.Name.Value), typeExpr(field.Type))
		if text := describeRaw(field.Description); text != "" {
			fmt.Fprintf(buffer, "\t\t\t\tDescription: %s,\n", text)
		}
		if reason, ok := deprecation(field.Directives); ok {
			fmt.Fprintf(buffer, "\t\t\t\tDeprecationReason: %s,\n", quote(reason))
		}
		if len(field.Arguments) != 0 {
			total.arguments += len(field.Arguments)
			buffer.WriteString("\t\t\t\tArgs: graphql.FieldConfigArgument{\n")
			emitInputValues(buffer, field.Arguments, "\t\t\t\t\t")
			buffer.WriteString("\t\t\t\t},\n")
		}
		buffer.WriteString("\t\t\t},\n")
	}
}

func emitInput(buffer *bytes.Buffer, node *ast.InputObjectDefinition, total *stats) {
	name := node.Name.Value
	total.inputFields += len(node.Fields)
	fmt.Fprintf(buffer, "\nfunc (r *Registry) %s() {\n\tr.input(%s, %s, func() graphql.InputObjectConfigFieldMap {\n\t\treturn graphql.InputObjectConfigFieldMap{\n",
		methodName(name), quote(name), describe(node.Description))
	emitInputValues(buffer, node.Fields, "\t\t\t")
	buffer.WriteString("\t\t}\n\t})\n}\n")
}

func emitInputValues(buffer *bytes.Buffer, values []*ast.InputValueDefinition, indent string) {
	sorted := make([]*ast.InputValueDefinition, len(values))
	copy(sorted, values)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name.Value < sorted[j].Name.Value })
	for _, value := range sorted {
		fmt.Fprintf(buffer, "%s%s: {\n%s\tType: %s,\n", indent, quote(value.Name.Value), indent, typeExpr(value.Type))
		if value.DefaultValue != nil {
			fmt.Fprintf(buffer, "%s\tDefaultValue: %s,\n", indent, defaultExpr(value.DefaultValue))
		}
		if text := describeRaw(value.Description); text != "" {
			fmt.Fprintf(buffer, "%s\tDescription: %s,\n", indent, text)
		}
		fmt.Fprintf(buffer, "%s},\n", indent)
	}
}

func emitUnion(buffer *bytes.Buffer, node *ast.UnionDefinition) {
	members := make([]string, 0, len(node.Types))
	for _, member := range node.Types {
		members = append(members, member.Name.Value)
	}
	sort.Strings(members)
	quoted := make([]string, 0, len(members))
	for _, member := range members {
		quoted = append(quoted, quote(member))
	}
	fmt.Fprintf(buffer, "\nfunc (r *Registry) %s() {\n\tr.union(%s, %s, []string{%s})\n}\n",
		methodName(node.Name.Value), quote(node.Name.Value), describe(node.Description), strings.Join(quoted, ", "))
}

func emitEnum(buffer *bytes.Buffer, node *ast.EnumDefinition) {
	name := node.Name.Value
	values := make([]*ast.EnumValueDefinition, len(node.Values))
	copy(values, node.Values)
	sort.Slice(values, func(i, j int) bool { return values[i].Name.Value < values[j].Name.Value })
	fmt.Fprintf(buffer, "\nfunc (r *Registry) %s() {\n\tr.enum(%s, %s, graphql.EnumValueConfigMap{\n",
		methodName(name), quote(name), describe(node.Description))
	for _, value := range values {
		// The internal value is the SDL name: GitHub's enums are string
		// enums on the wire, and internal/graphqlapi's hand-written enums
		// already spell Value as the name, so a resolver moved onto a
		// generated enum serializes identically.
		fmt.Fprintf(buffer, "\t\t%s: {\n\t\t\tValue: %s,\n", quote(value.Name.Value), quote(value.Name.Value))
		if text := describeRaw(value.Description); text != "" {
			fmt.Fprintf(buffer, "\t\t\tDescription: %s,\n", text)
		}
		if reason, ok := deprecation(value.Directives); ok {
			fmt.Fprintf(buffer, "\t\t\tDeprecationReason: %s,\n", quote(reason))
		}
		buffer.WriteString("\t\t},\n")
	}
	buffer.WriteString("\t})\n}\n")
}

func emitScalar(buffer *bytes.Buffer, node *ast.ScalarDefinition) {
	fmt.Fprintf(buffer, "\nfunc (r *Registry) %s() {\n\tr.scalar(%s, %s)\n}\n",
		methodName(node.Name.Value), quote(node.Name.Value), describe(node.Description))
}

func interfaceList(interfaces []*ast.Named) string {
	if len(interfaces) == 0 {
		return "nil"
	}
	names := make([]string, 0, len(interfaces))
	for _, item := range interfaces {
		names = append(names, quote(item.Name.Value))
	}
	sort.Strings(names)
	return "[]string{" + strings.Join(names, ", ") + "}"
}

func typeExpr(value ast.Type) string {
	switch typed := value.(type) {
	case *ast.NonNull:
		return "graphql.NewNonNull(" + typeExpr(typed.Type) + ")"
	case *ast.List:
		return "graphql.NewList(" + typeExpr(typed.Type) + ")"
	case *ast.Named:
		return "r.t(" + quote(typed.Name.Value) + ")"
	default:
		panic(fmt.Sprintf("graphqlschemagen: unsupported type node %T", value))
	}
}

// defaultExpr renders an SDL default value as the Go value graphql-go
// coerces back into a literal for introspection: enum defaults become
// their name (the internal value the generated enums use), input-object
// defaults become maps, and list defaults become []interface{}.
func defaultExpr(value ast.Value) string {
	switch typed := value.(type) {
	case *ast.IntValue:
		return typed.Value
	case *ast.FloatValue:
		return typed.Value
	case *ast.StringValue:
		return quote(typed.Value)
	case *ast.BooleanValue:
		return strconv.FormatBool(typed.Value)
	case *ast.EnumValue:
		return quote(typed.Value)
	case *ast.ListValue:
		items := make([]string, 0, len(typed.Values))
		for _, item := range typed.Values {
			items = append(items, defaultExpr(item))
		}
		return "[]interface{}{" + strings.Join(items, ", ") + "}"
	case *ast.ObjectValue:
		fields := make([]*ast.ObjectField, len(typed.Fields))
		copy(fields, typed.Fields)
		sort.Slice(fields, func(i, j int) bool { return fields[i].Name.Value < fields[j].Name.Value })
		items := make([]string, 0, len(fields))
		for _, field := range fields {
			items = append(items, quote(field.Name.Value)+": "+defaultExpr(field.Value))
		}
		return "map[string]interface{}{" + strings.Join(items, ", ") + "}"
	default:
		panic(fmt.Sprintf("graphqlschemagen: unsupported default value %T", value))
	}
}

func deprecation(directives []*ast.Directive) (string, bool) {
	for _, directive := range directives {
		if directive.Name.Value != "deprecated" {
			continue
		}
		for _, argument := range directive.Arguments {
			if argument.Name.Value != "reason" {
				continue
			}
			if text, ok := argument.Value.(*ast.StringValue); ok {
				return text.Value, true
			}
		}
		// GraphQL's @deprecated defaults its reason; spell the default so
		// introspection reports the same string GitHub does.
		return "No longer supported", true
	}
	return "", false
}

func describe(value *ast.StringValue) string {
	if value == nil {
		return `""`
	}
	return quote(value.Value)
}

func describeRaw(value *ast.StringValue) string {
	if value == nil || value.Value == "" {
		return ""
	}
	return quote(value.Value)
}

func quote(value string) string { return strconv.Quote(value) }

func writeGenerated(dir string, files map[string][]byte) error {
	existing, err := filepath.Glob(filepath.Join(dir, "*_gen.go"))
	if err != nil {
		return err
	}
	for _, path := range existing {
		if _, keep := files[filepath.Base(path)]; keep {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		// #nosec G306 -- generated Go source is committed and world-readable.
		if err := os.WriteFile(filepath.Join(dir, name), files[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}
