// Code generated by internal/graphqlschemagen. DO NOT EDIT.
// Source: third_party/github-graphql-schema.graphql.gz

package graphqlschema

import "github.com/graphql-go/graphql"

func (r *Registry) defineViewerHovercardContext() {
	r.object("ViewerHovercardContext", "A hovercard context with a message describing how the viewer is related.", []string{"HovercardContext"}, func() graphql.Fields {
		return graphql.Fields{
			"message": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A string describing this context",
			},
			"octicon": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "An octicon to accompany this context",
			},
			"viewer": {
				Type:        graphql.NewNonNull(r.t("User")),
				Description: "Identifies the user who is related to this context.",
			},
		}
	})
}

func (r *Registry) defineVotable() {
	r.interfaceType("Votable", "A subject that may be upvoted.", func() graphql.Fields {
		return graphql.Fields{
			"upvoteCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Number of upvotes that this subject has received.",
			},
			"viewerCanUpvote": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether or not the current user can add or remove an upvote on this subject.",
			},
			"viewerHasUpvoted": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether or not the current user has already upvoted this subject.",
			},
		}
	})
}

func (r *Registry) defineWorkflow() {
	r.object("Workflow", "A workflow contains meta information about an Actions workflow file.", []string{"Node", "UniformResourceLocatable"}, func() graphql.Fields {
		return graphql.Fields{
			"createdAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "Identifies the date and time when the object was created.",
			},
			"databaseId": {
				Type:        r.t("Int"),
				Description: "Identifies the primary key from the database.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the Workflow object",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the workflow.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this workflow",
			},
			"runs": {
				Type:        graphql.NewNonNull(r.t("WorkflowRunConnection")),
				Description: "The runs of the workflow.",
				Args: graphql.FieldConfigArgument{
					"after": {
						Type:        r.t("String"),
						Description: "Returns the elements in the list that come after the specified cursor.",
					},
					"before": {
						Type:        r.t("String"),
						Description: "Returns the elements in the list that come before the specified cursor.",
					},
					"first": {
						Type:        r.t("Int"),
						Description: "Returns the first _n_ elements from the list.",
					},
					"last": {
						Type:        r.t("Int"),
						Description: "Returns the last _n_ elements from the list.",
					},
					"orderBy": {
						Type:         r.t("WorkflowRunOrder"),
						DefaultValue: map[string]interface{}{"direction": "DESC", "field": "CREATED_AT"},
						Description:  "Ordering options for the connection",
					},
				},
			},
			"state": {
				Type:        graphql.NewNonNull(r.t("WorkflowState")),
				Description: "The state of the workflow.",
			},
			"updatedAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "Identifies the date and time when the object was last updated.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this workflow",
			},
		}
	})
}

func (r *Registry) defineWorkflowFileReference() {
	r.object("WorkflowFileReference", "A workflow that must run for this rule to pass", nil, func() graphql.Fields {
		return graphql.Fields{
			"path": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The path to the workflow file",
			},
			"ref": {
				Type:        r.t("String"),
				Description: "The ref (branch or tag) of the workflow file to use",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "The ID of the repository where the workflow is defined",
			},
			"sha": {
				Type:        r.t("String"),
				Description: "The commit SHA of the workflow file to use",
			},
		}
	})
}

func (r *Registry) defineWorkflowFileReferenceInput() {
	r.input("WorkflowFileReferenceInput", "A workflow that must run for this rule to pass", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"path": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The path to the workflow file",
			},
			"ref": {
				Type:        r.t("String"),
				Description: "The ref (branch or tag) of the workflow file to use",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "The ID of the repository where the workflow is defined",
			},
			"sha": {
				Type:        r.t("String"),
				Description: "The commit SHA of the workflow file to use",
			},
		}
	})
}

func (r *Registry) defineWorkflowRun() {
	r.object("WorkflowRun", "A workflow run.", []string{"Node", "UniformResourceLocatable"}, func() graphql.Fields {
		return graphql.Fields{
			"checkSuite": {
				Type:        graphql.NewNonNull(r.t("CheckSuite")),
				Description: "The check suite this workflow run belongs to.",
			},
			"createdAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "Identifies the date and time when the object was created.",
			},
			"databaseId": {
				Type:        r.t("Int"),
				Description: "Identifies the primary key from the database.",
			},
			"deploymentReviews": {
				Type:        graphql.NewNonNull(r.t("DeploymentReviewConnection")),
				Description: "The log of deployment reviews",
				Args: graphql.FieldConfigArgument{
					"after": {
						Type:        r.t("String"),
						Description: "Returns the elements in the list that come after the specified cursor.",
					},
					"before": {
						Type:        r.t("String"),
						Description: "Returns the elements in the list that come before the specified cursor.",
					},
					"first": {
						Type:        r.t("Int"),
						Description: "Returns the first _n_ elements from the list.",
					},
					"last": {
						Type:        r.t("Int"),
						Description: "Returns the last _n_ elements from the list.",
					},
				},
			},
			"displayTitle": {
				Type:        r.t("String"),
				Description: "The human-readable title of the workflow run.",
			},
			"event": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The event that triggered the workflow run",
			},
			"file": {
				Type:        r.t("WorkflowRunFile"),
				Description: "The workflow file",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the WorkflowRun object",
			},
			"pendingDeploymentRequests": {
				Type:        graphql.NewNonNull(r.t("DeploymentRequestConnection")),
				Description: "The pending deployment requests of all check runs in this workflow run",
				Args: graphql.FieldConfigArgument{
					"after": {
						Type:        r.t("String"),
						Description: "Returns the elements in the list that come after the specified cursor.",
					},
					"before": {
						Type:        r.t("String"),
						Description: "Returns the elements in the list that come before the specified cursor.",
					},
					"first": {
						Type:        r.t("Int"),
						Description: "Returns the first _n_ elements from the list.",
					},
					"last": {
						Type:        r.t("Int"),
						Description: "Returns the last _n_ elements from the list.",
					},
				},
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this workflow run",
			},
			"runAttempt": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "The attempt number of this workflow run.",
			},
			"runNumber": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "A number that uniquely identifies this workflow run in its parent workflow.",
			},
			"updatedAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "Identifies the date and time when the object was last updated.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this workflow run",
			},
			"workflow": {
				Type:        graphql.NewNonNull(r.t("Workflow")),
				Description: "The workflow executed in this workflow run.",
			},
		}
	})
}

func (r *Registry) defineWorkflowRunConnection() {
	r.object("WorkflowRunConnection", "The connection type for WorkflowRun.", nil, func() graphql.Fields {
		return graphql.Fields{
			"edges": {
				Type:        graphql.NewList(r.t("WorkflowRunEdge")),
				Description: "A list of edges.",
			},
			"nodes": {
				Type:        graphql.NewList(r.t("WorkflowRun")),
				Description: "A list of nodes.",
			},
			"pageInfo": {
				Type:        graphql.NewNonNull(r.t("PageInfo")),
				Description: "Information to aid in pagination.",
			},
			"totalCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Identifies the total count of items in the connection.",
			},
		}
	})
}

func (r *Registry) defineWorkflowRunEdge() {
	r.object("WorkflowRunEdge", "An edge in a connection.", nil, func() graphql.Fields {
		return graphql.Fields{
			"cursor": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A cursor for use in pagination.",
			},
			"node": {
				Type:        r.t("WorkflowRun"),
				Description: "The item at the end of the edge.",
			},
		}
	})
}

func (r *Registry) defineWorkflowRunFile() {
	r.object("WorkflowRunFile", "An executed workflow file for a workflow run.", []string{"Node", "UniformResourceLocatable"}, func() graphql.Fields {
		return graphql.Fields{
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the WorkflowRunFile object",
			},
			"path": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The path of the workflow file relative to its repository.",
			},
			"repositoryFileUrl": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The direct link to the file in the repository which stores the workflow file.",
			},
			"repositoryName": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The repository name and owner which stores the workflow file.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this workflow run file",
			},
			"run": {
				Type:        graphql.NewNonNull(r.t("WorkflowRun")),
				Description: "The parent workflow run execution for this file.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this workflow run file",
			},
			"viewerCanPushRepository": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "If the viewer has permissions to push to the repository which stores the workflow.",
			},
			"viewerCanReadRepository": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "If the viewer has permissions to read the repository which stores the workflow.",
			},
		}
	})
}

func (r *Registry) defineWorkflowRunOrder() {
	r.input("WorkflowRunOrder", "Ways in which lists of workflow runs can be ordered upon return.", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"direction": {
				Type:        graphql.NewNonNull(r.t("OrderDirection")),
				Description: "The direction in which to order workflow runs by the specified field.",
			},
			"field": {
				Type:        graphql.NewNonNull(r.t("WorkflowRunOrderField")),
				Description: "The field by which to order workflows.",
			},
		}
	})
}

func (r *Registry) defineWorkflowRunOrderField() {
	r.enum("WorkflowRunOrderField", "Properties by which workflow run connections can be ordered.", graphql.EnumValueConfigMap{
		"CREATED_AT": {
			Value:       "CREATED_AT",
			Description: "Order workflow runs by most recently created",
		},
	})
}

func (r *Registry) defineWorkflowState() {
	r.enum("WorkflowState", "The possible states for a workflow.", graphql.EnumValueConfigMap{
		"ACTIVE": {
			Value:       "ACTIVE",
			Description: "The workflow is active.",
		},
		"DELETED": {
			Value:       "DELETED",
			Description: "The workflow was deleted from the git repository.",
		},
		"DISABLED_FORK": {
			Value:       "DISABLED_FORK",
			Description: "The workflow was disabled by default on a fork.",
		},
		"DISABLED_INACTIVITY": {
			Value:       "DISABLED_INACTIVITY",
			Description: "The workflow was disabled for inactivity in the repository.",
		},
		"DISABLED_MANUALLY": {
			Value:       "DISABLED_MANUALLY",
			Description: "The workflow was disabled manually.",
		},
	})
}

func (r *Registry) defineWorkflowsParameters() {
	r.object("WorkflowsParameters", "Require all changes made to a targeted branch to pass the specified workflows before they can be merged.", nil, func() graphql.Fields {
		return graphql.Fields{
			"doNotEnforceOnCreate": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Allow repositories and branches to be created if a check would otherwise prohibit it.",
			},
			"workflows": {
				Type:        graphql.NewNonNull(graphql.NewList(graphql.NewNonNull(r.t("WorkflowFileReference")))),
				Description: "Workflows that must pass for this rule to pass.",
			},
		}
	})
}

func (r *Registry) defineWorkflowsParametersInput() {
	r.input("WorkflowsParametersInput", "Require all changes made to a targeted branch to pass the specified workflows before they can be merged.", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"doNotEnforceOnCreate": {
				Type:        r.t("Boolean"),
				Description: "Allow repositories and branches to be created if a check would otherwise prohibit it.",
			},
			"workflows": {
				Type:        graphql.NewNonNull(graphql.NewList(graphql.NewNonNull(r.t("WorkflowFileReferenceInput")))),
				Description: "Workflows that must pass for this rule to pass.",
			},
		}
	})
}

func (r *Registry) defineX509Certificate() {
	r.scalar("X509Certificate", "A valid x509 certificate string")
}
