// Code generated by internal/graphqlschemagen. DO NOT EDIT.
// Source: third_party/github-graphql-schema.graphql.gz

package graphqlschema

import "github.com/graphql-go/graphql"

func (r *Registry) defineCreateDeploymentStatusInput() {
	r.input("CreateDeploymentStatusInput", "Autogenerated input type of CreateDeploymentStatus", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"autoInactive": {
				Type:         r.t("Boolean"),
				DefaultValue: true,
				Description:  "Adds a new inactive status to all non-transient, non-production environment\ndeployments with the same repository and environment name as the created\nstatus's deployment.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"deploymentId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The node ID of the deployment.",
			},
			"description": {
				Type:         r.t("String"),
				DefaultValue: "",
				Description:  "A short description of the status. Maximum length of 140 characters.",
			},
			"environment": {
				Type:        r.t("String"),
				Description: "If provided, updates the environment of the deploy. Otherwise, does not modify the environment.",
			},
			"environmentUrl": {
				Type:         r.t("String"),
				DefaultValue: "",
				Description:  "Sets the URL for accessing your environment.",
			},
			"logUrl": {
				Type:         r.t("String"),
				DefaultValue: "",
				Description:  "The log URL to associate with this status.       This URL should contain\noutput to keep the user updated while the task is running       or serve as\nhistorical information for what happened in the deployment.",
			},
			"state": {
				Type:        graphql.NewNonNull(r.t("DeploymentStatusState")),
				Description: "The state of the deployment.",
			},
		}
	})
}

func (r *Registry) defineCreateDeploymentStatusPayload() {
	r.object("CreateDeploymentStatusPayload", "Autogenerated return type of CreateDeploymentStatus.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"deploymentStatus": {
				Type:        r.t("DeploymentStatus"),
				Description: "The new deployment status.",
			},
		}
	})
}

func (r *Registry) defineCreateDiscussionInput() {
	r.input("CreateDiscussionInput", "Autogenerated input type of CreateDiscussion", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"body": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The body of the discussion.",
			},
			"categoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The id of the discussion category to associate with this discussion.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The id of the repository on which to create the discussion.",
			},
			"title": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The title of the discussion.",
			},
		}
	})
}

func (r *Registry) defineCreateDiscussionPayload() {
	r.object("CreateDiscussionPayload", "Autogenerated return type of CreateDiscussion.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"discussion": {
				Type:        r.t("Discussion"),
				Description: "The discussion that was just created.",
			},
		}
	})
}

func (r *Registry) defineCreateEnterpriseOrganizationInput() {
	r.input("CreateEnterpriseOrganizationInput", "Autogenerated input type of CreateEnterpriseOrganization", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"adminLogins": {
				Type:        graphql.NewNonNull(graphql.NewList(graphql.NewNonNull(r.t("String")))),
				Description: "The logins for the administrators of the new organization.",
			},
			"billingEmail": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The email used for sending billing receipts.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"enterpriseId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the enterprise owning the new organization.",
			},
			"login": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The login of the new organization.",
			},
			"profileName": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The profile name of the new organization.",
			},
		}
	})
}

func (r *Registry) defineCreateEnterpriseOrganizationPayload() {
	r.object("CreateEnterpriseOrganizationPayload", "Autogenerated return type of CreateEnterpriseOrganization.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"enterprise": {
				Type:        r.t("Enterprise"),
				Description: "The enterprise that owns the created organization.",
			},
			"organization": {
				Type:        r.t("Organization"),
				Description: "The organization that was created.",
			},
		}
	})
}

func (r *Registry) defineCreateEnvironmentInput() {
	r.input("CreateEnvironmentInput", "Autogenerated input type of CreateEnvironment", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the environment.",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The node ID of the repository.",
			},
		}
	})
}

func (r *Registry) defineCreateEnvironmentPayload() {
	r.object("CreateEnvironmentPayload", "Autogenerated return type of CreateEnvironment.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"environment": {
				Type:        r.t("Environment"),
				Description: "The new or existing environment.",
			},
		}
	})
}

func (r *Registry) defineCreateIpAllowListEntryInput() {
	r.input("CreateIpAllowListEntryInput", "Autogenerated input type of CreateIpAllowListEntry", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"allowListValue": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "An IP address or range of addresses in CIDR notation.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"isActive": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether the IP allow list entry is active when an IP allow list is enabled.",
			},
			"name": {
				Type:        r.t("String"),
				Description: "An optional name for the IP allow list entry.",
			},
			"ownerId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the owner for which to create the new IP allow list entry.",
			},
		}
	})
}

func (r *Registry) defineCreateIpAllowListEntryPayload() {
	r.object("CreateIpAllowListEntryPayload", "Autogenerated return type of CreateIpAllowListEntry.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"ipAllowListEntry": {
				Type:        r.t("IpAllowListEntry"),
				Description: "The IP allow list entry that was created.",
			},
		}
	})
}

func (r *Registry) defineCreateIssueFieldInput() {
	r.input("CreateIssueFieldInput", "Autogenerated input type of CreateIssueField", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"dataType": {
				Type:        graphql.NewNonNull(r.t("IssueFieldDataType")),
				Description: "The data type of the issue field.",
			},
			"description": {
				Type:        r.t("String"),
				Description: "A description of the issue field.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the issue field.",
			},
			"options": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("IssueFieldSingleSelectOptionInput"))),
				Description: "The options for the issue field if applicable.",
			},
			"ownerId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the organization where the issue field will be created.",
			},
			"visibility": {
				Type:        r.t("IssueFieldVisibility"),
				Description: "The visibility of the issue field.",
			},
		}
	})
}

func (r *Registry) defineCreateIssueFieldPayload() {
	r.object("CreateIssueFieldPayload", "Autogenerated return type of CreateIssueField.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueField": {
				Type:        r.t("IssueFields"),
				Description: "The newly created issue field.",
			},
		}
	})
}

func (r *Registry) defineCreateIssueFieldValueInput() {
	r.input("CreateIssueFieldValueInput", "Autogenerated input type of CreateIssueFieldValue", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueField": {
				Type:        graphql.NewNonNull(r.t("IssueFieldCreateOrUpdateInput")),
				Description: "The field value to create.",
			},
			"issueId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the issue.",
			},
		}
	})
}

func (r *Registry) defineCreateIssueFieldValuePayload() {
	r.object("CreateIssueFieldValuePayload", "Autogenerated return type of CreateIssueFieldValue.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issue": {
				Type:        r.t("Issue"),
				Description: "The issue object.",
			},
			"issueFieldValue": {
				Type:        r.t("IssueFieldValue"),
				Description: "The newly created issue field value.",
			},
		}
	})
}

func (r *Registry) defineCreateIssueInput() {
	r.input("CreateIssueInput", "Autogenerated input type of CreateIssue", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"agentAssignment": {
				Type:        r.t("AgentAssignmentInput"),
				Description: "Configuration for assigning Copilot to this issue.",
			},
			"assigneeIds": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ID"))),
				Description: "The Node ID of assignees for this issue.",
			},
			"body": {
				Type:        r.t("String"),
				Description: "The body for the issue description.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueFields": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("IssueFieldCreateOrUpdateInput"))),
				Description: "An array of issue fields to set on the issue during creation",
			},
			"issueTemplate": {
				Type:        r.t("String"),
				Description: "The name of an issue template in the repository, assigns labels and assignees from the template to the issue",
			},
			"issueTypeId": {
				Type:        r.t("ID"),
				Description: "The Node ID of the issue type for this issue",
			},
			"labelIds": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ID"))),
				Description: "An array of Node IDs of labels for this issue.",
			},
			"milestoneId": {
				Type:        r.t("ID"),
				Description: "The Node ID of the milestone for this issue.",
			},
			"parentIssueId": {
				Type:        r.t("ID"),
				Description: "The Node ID of the parent issue to add this new issue to",
			},
			"projectIds": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ID"))),
				Description: "An array of Node IDs for projects associated with this issue.",
			},
			"projectV2Ids": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ID"))),
				Description: "An array of Node IDs for Projects V2 associated with this issue.",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the repository.",
			},
			"title": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The title for the issue.",
			},
		}
	})
}

func (r *Registry) defineCreateIssuePayload() {
	r.object("CreateIssuePayload", "Autogenerated return type of CreateIssue.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issue": {
				Type:        r.t("Issue"),
				Description: "The new issue.",
			},
		}
	})
}

func (r *Registry) defineCreateIssueTypeInput() {
	r.input("CreateIssueTypeInput", "Autogenerated input type of CreateIssueType", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"color": {
				Type:        r.t("IssueTypeColor"),
				Description: "Color for the issue type",
			},
			"description": {
				Type:        r.t("String"),
				Description: "Description of the new issue type",
			},
			"isEnabled": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether or not the issue type is enabled on the org level",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "Name of the new issue type",
			},
			"ownerId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID for the organization on which the issue type is created",
			},
		}
	})
}

func (r *Registry) defineCreateIssueTypePayload() {
	r.object("CreateIssueTypePayload", "Autogenerated return type of CreateIssueType.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueType": {
				Type:        r.t("IssueType"),
				Description: "The newly created issue type",
			},
		}
	})
}

func (r *Registry) defineCreateLabelInput() {
	r.input("CreateLabelInput", "Autogenerated input type of CreateLabel", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"color": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A 6 character hex code, without the leading #, identifying the color of the label.",
			},
			"description": {
				Type:        r.t("String"),
				Description: "A brief description of the label, such as its purpose.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the label.",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the repository.",
			},
		}
	})
}

func (r *Registry) defineCreateLabelPayload() {
	r.object("CreateLabelPayload", "Autogenerated return type of CreateLabel.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"label": {
				Type:        r.t("Label"),
				Description: "The new label.",
			},
		}
	})
}

func (r *Registry) defineCreateLinkedBranchInput() {
	r.input("CreateLinkedBranchInput", "Autogenerated input type of CreateLinkedBranch", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "ID of the issue to link to.",
			},
			"name": {
				Type:        r.t("String"),
				Description: "The name of the new branch. Defaults to issue number and title.",
			},
			"oid": {
				Type:        graphql.NewNonNull(r.t("GitObjectID")),
				Description: "The commit SHA to base the new branch on.",
			},
			"repositoryId": {
				Type:        r.t("ID"),
				Description: "ID of the repository to create the branch in. Defaults to the issue repository.",
			},
		}
	})
}

func (r *Registry) defineCreateLinkedBranchPayload() {
	r.object("CreateLinkedBranchPayload", "Autogenerated return type of CreateLinkedBranch.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issue": {
				Type:        r.t("Issue"),
				Description: "The issue that was linked to.",
			},
			"linkedBranch": {
				Type:        r.t("LinkedBranch"),
				Description: "The new branch issue reference.",
			},
		}
	})
}

func (r *Registry) defineCreateMigrationSourceInput() {
	r.input("CreateMigrationSourceInput", "Autogenerated input type of CreateMigrationSource", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"accessToken": {
				Type:        r.t("String"),
				Description: "The migration source access token.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"githubPat": {
				Type:        r.t("String"),
				Description: "The GitHub personal access token of the user importing to the target repository.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The migration source name.",
			},
			"ownerId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the organization that will own the migration source.",
			},
			"type": {
				Type:        graphql.NewNonNull(r.t("MigrationSourceType")),
				Description: "The migration source type.",
			},
			"url": {
				Type:        r.t("String"),
				Description: "The migration source URL, for example `https://github.com` or `https://monalisa.ghe.com`.",
			},
		}
	})
}

func (r *Registry) defineCreateMigrationSourcePayload() {
	r.object("CreateMigrationSourcePayload", "Autogenerated return type of CreateMigrationSource.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"migrationSource": {
				Type:        r.t("MigrationSource"),
				Description: "The created migration source.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectInput() {
	r.input("CreateProjectInput", "Autogenerated input type of CreateProject", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"body": {
				Type:        r.t("String"),
				Description: "The description of project.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of project.",
			},
			"ownerId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The owner ID to create the project under.",
			},
			"repositoryIds": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ID"))),
				Description: "A list of repository IDs to create as linked repositories for the project",
			},
			"template": {
				Type:        r.t("ProjectTemplate"),
				Description: "The name of the GitHub-provided template.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectPayload() {
	r.object("CreateProjectPayload", "Autogenerated return type of CreateProject.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"project": {
				Type:        r.t("Project"),
				Description: "The new project.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2FieldInput() {
	r.input("CreateProjectV2FieldInput", "Autogenerated input type of CreateProjectV2Field", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"dataType": {
				Type:        graphql.NewNonNull(r.t("ProjectV2CustomFieldType")),
				Description: "The data type of the field.",
			},
			"iterationConfiguration": {
				Type:        r.t("ProjectV2IterationFieldConfigurationInput"),
				Description: "Configuration for an iteration field.",
			},
			"multiSelectOptions": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ProjectV2MultiSelectFieldOptionInput"))),
				Description: "Options for a multi select field. At least one value is required if data_type is MULTI_SELECT",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the field.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the Project to create the field in.",
			},
			"singleSelectOptions": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("ProjectV2SingleSelectFieldOptionInput"))),
				Description: "Options for a single select field. At least one value is required if data_type is SINGLE_SELECT",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2FieldPayload() {
	r.object("CreateProjectV2FieldPayload", "Autogenerated return type of CreateProjectV2Field.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectV2Field": {
				Type:        r.t("ProjectV2FieldConfiguration"),
				Description: "The new field.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2Input() {
	r.input("CreateProjectV2Input", "Autogenerated input type of CreateProjectV2", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"ownerId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The owner ID to create the project under.",
			},
			"repositoryId": {
				Type:        r.t("ID"),
				Description: "The repository to link the project to.",
			},
			"teamId": {
				Type:        r.t("ID"),
				Description: "The team to link the project to. The team will be granted read permissions.",
			},
			"title": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The title of the project.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2IssueFieldInput() {
	r.input("CreateProjectV2IssueFieldInput", "Autogenerated input type of CreateProjectV2IssueField", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueFieldId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the IssueField to create the field for.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the Project to create the field in.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2IssueFieldPayload() {
	r.object("CreateProjectV2IssueFieldPayload", "Autogenerated return type of CreateProjectV2IssueField.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectV2Field": {
				Type:        r.t("ProjectV2FieldConfiguration"),
				Description: "The new field.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2Payload() {
	r.object("CreateProjectV2Payload", "Autogenerated return type of CreateProjectV2.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectV2": {
				Type:        r.t("ProjectV2"),
				Description: "The new project.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2StatusUpdateInput() {
	r.input("CreateProjectV2StatusUpdateInput", "Autogenerated input type of CreateProjectV2StatusUpdate", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"body": {
				Type:        r.t("String"),
				Description: "The body of the status update.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the Project to create the status update in.",
			},
			"startDate": {
				Type:        r.t("Date"),
				Description: "The start date of the status update.",
			},
			"status": {
				Type:        r.t("ProjectV2StatusUpdateStatus"),
				Description: "The status of the status update.",
			},
			"targetDate": {
				Type:        r.t("Date"),
				Description: "The target date of the status update.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2StatusUpdatePayload() {
	r.object("CreateProjectV2StatusUpdatePayload", "Autogenerated return type of CreateProjectV2StatusUpdate.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"statusUpdate": {
				Type:        r.t("ProjectV2StatusUpdate"),
				Description: "The status update updated in the project.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2ViewInput() {
	r.input("CreateProjectV2ViewInput", "Autogenerated input type of CreateProjectV2View", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"configuration": {
				Type:        r.t("ProjectV2ViewConfigurationInput"),
				Description: "The configuration for the view.",
			},
			"layout": {
				Type:        graphql.NewNonNull(r.t("ProjectV2ViewLayout")),
				Description: "The layout of the view.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the view.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the project to create a view in.",
			},
		}
	})
}

func (r *Registry) defineCreateProjectV2ViewPayload() {
	r.object("CreateProjectV2ViewPayload", "Autogenerated return type of CreateProjectV2View.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectV2View": {
				Type:        r.t("ProjectV2View"),
				Description: "The new view.",
			},
		}
	})
}

func (r *Registry) defineCreatePullRequestInput() {
	r.input("CreatePullRequestInput", "Autogenerated input type of CreatePullRequest", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"baseRefName": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the branch you want your changes pulled into. This should be an existing branch\non the current repository. You cannot update the base branch on a pull request to point\nto another repository.",
			},
			"body": {
				Type:        r.t("String"),
				Description: "The contents of the pull request.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"draft": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Indicates whether this pull request should be a draft.",
			},
			"headRefName": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the branch where your changes are implemented. For cross-repository pull requests\nin the same network, namespace `head_ref_name` with a user like this: `username:branch`.",
			},
			"headRepositoryId": {
				Type:        r.t("ID"),
				Description: "The Node ID of the head repository.",
			},
			"maintainerCanModify": {
				Type:         r.t("Boolean"),
				DefaultValue: true,
				Description:  "Indicates whether maintainers can modify the pull request.",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the repository.",
			},
			"title": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The title of the pull request.",
			},
		}
	})
}

func (r *Registry) defineCreatePullRequestPayload() {
	r.object("CreatePullRequestPayload", "Autogenerated return type of CreatePullRequest.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"pullRequest": {
				Type:        r.t("PullRequest"),
				Description: "The new pull request.",
			},
		}
	})
}

func (r *Registry) defineCreateRefInput() {
	r.input("CreateRefInput", "Autogenerated input type of CreateRef", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The fully qualified name of the new Ref (ie: `refs/heads/my_new_branch`).",
			},
			"oid": {
				Type:        graphql.NewNonNull(r.t("GitObjectID")),
				Description: "The GitObjectID that the new Ref shall target. Must point to a commit.",
			},
			"repositoryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the Repository to create the Ref in.",
			},
		}
	})
}

func (r *Registry) defineCreateRefPayload() {
	r.object("CreateRefPayload", "Autogenerated return type of CreateRef.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"ref": {
				Type:        r.t("Ref"),
				Description: "The newly created ref.",
			},
		}
	})
}

func (r *Registry) defineCreateRepositoryCustomPropertyInput() {
	r.input("CreateRepositoryCustomPropertyInput", "Autogenerated input type of CreateRepositoryCustomProperty", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"allowedValues": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("String"))),
				Description: "The allowed values for the custom property.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"defaultValue": {
				Type:        r.t("String"),
				Description: "The default value for the custom property if the property is required.",
			},
			"description": {
				Type:        r.t("String"),
				Description: "The description of the custom property.",
			},
			"propertyName": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the custom property.",
			},
			"regex": {
				Type:        r.t("String"),
				Description: "The regex pattern that the value of the custom property must match, if the `value_type` is `string`.",
			},
			"requireExplicitValues": {
				Type:        r.t("Boolean"),
				Description: "Whether this repository custom property requires explicit values.",
			},
			"required": {
				Type:        r.t("Boolean"),
				Description: "Whether the custom property is required.",
			},
			"sourceId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The global relay id of the source in which a new custom property should be created in.",
			},
			"valueType": {
				Type:        graphql.NewNonNull(r.t("CustomPropertyValueType")),
				Description: "The value type for the custom property.",
			},
			"valuesEditableBy": {
				Type:        r.t("RepositoryCustomPropertyValuesEditableBy"),
				Description: "The allowed actors who can edit the values of a custom property.",
			},
		}
	})
}

func (r *Registry) defineCreateRepositoryCustomPropertyPayload() {
	r.object("CreateRepositoryCustomPropertyPayload", "Autogenerated return type of CreateRepositoryCustomProperty.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"repositoryCustomProperty": {
				Type:        r.t("RepositoryCustomProperty"),
				Description: "The newly created repository custom property.",
			},
		}
	})
}

func (r *Registry) defineCreateRepositoryInput() {
	r.input("CreateRepositoryInput", "Autogenerated input type of CreateRepository", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"description": {
				Type:        r.t("String"),
				Description: "A short description of the new repository.",
			},
			"hasIssuesEnabled": {
				Type:         r.t("Boolean"),
				DefaultValue: true,
				Description:  "Indicates if the repository should have the issues feature enabled.",
			},
			"hasWikiEnabled": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Indicates if the repository should have the wiki feature enabled.",
			},
			"homepageUrl": {
				Type:        r.t("URI"),
				Description: "The URL for a web page about this repository.",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the new repository.",
			},
			"ownerId": {
				Type:        r.t("ID"),
				Description: "The ID of the owner for the new repository.",
			},
			"teamId": {
				Type:        r.t("ID"),
				Description: "When an organization is specified as the owner, this ID identifies the team\nthat should be granted access to the new repository.",
			},
			"template": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Whether this repository should be marked as a template such that anyone who\ncan access it can create new repositories with the same files and directory structure.",
			},
			"visibility": {
				Type:        graphql.NewNonNull(r.t("RepositoryVisibility")),
				Description: "Indicates the repository's visibility level.",
			},
		}
	})
}

func (r *Registry) defineCreateRepositoryPayload() {
	r.object("CreateRepositoryPayload", "Autogenerated return type of CreateRepository.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"repository": {
				Type:        r.t("Repository"),
				Description: "The new repository.",
			},
		}
	})
}

func (r *Registry) defineCreateRepositoryRulesetInput() {
	r.input("CreateRepositoryRulesetInput", "Autogenerated input type of CreateRepositoryRuleset", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"bypassActors": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("RepositoryRulesetBypassActorInput"))),
				Description: "A list of actors that are allowed to bypass rules in this ruleset.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"conditions": {
				Type:        graphql.NewNonNull(r.t("RepositoryRuleConditionsInput")),
				Description: "The set of conditions for this ruleset",
			},
			"enforcement": {
				Type:        graphql.NewNonNull(r.t("RuleEnforcement")),
				Description: "The enforcement level for this ruleset",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the ruleset.",
			},
			"rules": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("RepositoryRuleInput"))),
				Description: "The list of rules for this ruleset",
			},
			"sourceId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The global relay id of the source in which a new ruleset should be created in.",
			},
			"target": {
				Type:        r.t("RepositoryRulesetTarget"),
				Description: "The target of the ruleset.",
			},
		}
	})
}

func (r *Registry) defineCreateRepositoryRulesetPayload() {
	r.object("CreateRepositoryRulesetPayload", "Autogenerated return type of CreateRepositoryRuleset.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"ruleset": {
				Type:        r.t("RepositoryRuleset"),
				Description: "The newly created Ruleset.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorsListingInput() {
	r.input("CreateSponsorsListingInput", "Autogenerated input type of CreateSponsorsListing", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"billingCountryOrRegionCode": {
				Type:        r.t("SponsorsCountryOrRegionCode"),
				Description: "The country or region where the sponsorable's bank account is located.\nRequired if fiscalHostLogin is not specified, ignored when fiscalHostLogin is specified.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"contactEmail": {
				Type:        r.t("String"),
				Description: "The email address we should use to contact you about the GitHub Sponsors\nprofile being created. This will not be shared publicly. Must be a verified\nemail address already on your GitHub account. Only relevant when the\nsponsorable is yourself. Defaults to your primary email address on file if omitted.",
			},
			"fiscalHostLogin": {
				Type:        r.t("String"),
				Description: "The username of the supported fiscal host's GitHub organization, if you want\nto receive sponsorship payouts through a fiscal host rather than directly to a\nbank account. For example, 'Open-Source-Collective' for Open Source Collective\nor 'numfocus' for numFOCUS. Case insensitive. See https://docs.github.com/sponsors/receiving-sponsorships-through-github-sponsors/using-a-fiscal-host-to-receive-github-sponsors-payouts\nfor more information.",
			},
			"fiscallyHostedProjectProfileUrl": {
				Type:        r.t("String"),
				Description: "The URL for your profile page on the fiscal host's website, e.g.,\nhttps://opencollective.com/babel or https://numfocus.org/project/bokeh.\nRequired if fiscalHostLogin is specified.",
			},
			"fullDescription": {
				Type:        r.t("String"),
				Description: "Provide an introduction to serve as the main focus that appears on your GitHub\nSponsors profile. It's a great opportunity to help potential sponsors learn\nmore about you, your work, and why their sponsorship is important to you.\nGitHub-flavored Markdown is supported.",
			},
			"residenceCountryOrRegionCode": {
				Type:        r.t("SponsorsCountryOrRegionCode"),
				Description: "The country or region where the sponsorable resides. This is for tax purposes.\nRequired if the sponsorable is yourself, ignored when sponsorableLogin\nspecifies an organization.",
			},
			"sponsorableLogin": {
				Type:        r.t("String"),
				Description: "The username of the organization to create a GitHub Sponsors profile for, if\ndesired. Defaults to creating a GitHub Sponsors profile for the authenticated\nuser if omitted.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorsListingPayload() {
	r.object("CreateSponsorsListingPayload", "Autogenerated return type of CreateSponsorsListing.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"sponsorsListing": {
				Type:        r.t("SponsorsListing"),
				Description: "The new GitHub Sponsors profile.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorsTierInput() {
	r.input("CreateSponsorsTierInput", "Autogenerated input type of CreateSponsorsTier", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"amount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "The value of the new tier in US dollars. Valid values: 1-12000.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"description": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A description of what this tier is, what perks sponsors might receive, what a sponsorship at this tier means for you, etc.",
			},
			"isRecurring": {
				Type:         r.t("Boolean"),
				DefaultValue: true,
				Description:  "Whether sponsorships using this tier should happen monthly/yearly or just once.",
			},
			"publish": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Whether to make the tier available immediately for sponsors to choose.\nDefaults to creating a draft tier that will not be publicly visible.",
			},
			"repositoryId": {
				Type:        r.t("ID"),
				Description: "Optional ID of the private repository that sponsors at this tier should gain\nread-only access to. Must be owned by an organization.",
			},
			"repositoryName": {
				Type:        r.t("String"),
				Description: "Optional name of the private repository that sponsors at this tier should gain\nread-only access to. Must be owned by an organization. Necessary if\nrepositoryOwnerLogin is given. Will be ignored if repositoryId is given.",
			},
			"repositoryOwnerLogin": {
				Type:        r.t("String"),
				Description: "Optional login of the organization owner of the private repository that\nsponsors at this tier should gain read-only access to. Necessary if\nrepositoryName is given. Will be ignored if repositoryId is given.",
			},
			"sponsorableId": {
				Type:        r.t("ID"),
				Description: "The ID of the user or organization who owns the GitHub Sponsors profile.\nDefaults to the current user if omitted and sponsorableLogin is not given.",
			},
			"sponsorableLogin": {
				Type:        r.t("String"),
				Description: "The username of the user or organization who owns the GitHub Sponsors profile.\nDefaults to the current user if omitted and sponsorableId is not given.",
			},
			"welcomeMessage": {
				Type:        r.t("String"),
				Description: "Optional message new sponsors at this tier will receive.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorsTierPayload() {
	r.object("CreateSponsorsTierPayload", "Autogenerated return type of CreateSponsorsTier.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"sponsorsTier": {
				Type:        r.t("SponsorsTier"),
				Description: "The new tier.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorshipInput() {
	r.input("CreateSponsorshipInput", "Autogenerated input type of CreateSponsorship", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"amount": {
				Type:        r.t("Int"),
				Description: "The amount to pay to the sponsorable in US dollars. Required if a tierId is not specified. Valid values: 1-12000.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"isRecurring": {
				Type:        r.t("Boolean"),
				Description: "Whether the sponsorship should happen monthly/yearly or just this one time. Required if a tierId is not specified.",
			},
			"privacyLevel": {
				Type:         r.t("SponsorshipPrivacy"),
				DefaultValue: "PUBLIC",
				Description:  "Specify whether others should be able to see that the sponsor is sponsoring\nthe sponsorable. Public visibility still does not reveal which tier is used.",
			},
			"receiveEmails": {
				Type:         r.t("Boolean"),
				DefaultValue: true,
				Description:  "Whether the sponsor should receive email updates from the sponsorable.",
			},
			"sponsorId": {
				Type:        r.t("ID"),
				Description: "The ID of the user or organization who is acting as the sponsor, paying for\nthe sponsorship. Required if sponsorLogin is not given.",
			},
			"sponsorLogin": {
				Type:        r.t("String"),
				Description: "The username of the user or organization who is acting as the sponsor, paying\nfor the sponsorship. Required if sponsorId is not given.",
			},
			"sponsorableId": {
				Type:        r.t("ID"),
				Description: "The ID of the user or organization who is receiving the sponsorship. Required if sponsorableLogin is not given.",
			},
			"sponsorableLogin": {
				Type:        r.t("String"),
				Description: "The username of the user or organization who is receiving the sponsorship. Required if sponsorableId is not given.",
			},
			"tierId": {
				Type:        r.t("ID"),
				Description: "The ID of one of sponsorable's existing tiers to sponsor at. Required if amount is not specified.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorshipPayload() {
	r.object("CreateSponsorshipPayload", "Autogenerated return type of CreateSponsorship.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"sponsorship": {
				Type:        r.t("Sponsorship"),
				Description: "The sponsorship that was started.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorshipsInput() {
	r.input("CreateSponsorshipsInput", "Autogenerated input type of CreateSponsorships", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"privacyLevel": {
				Type:         r.t("SponsorshipPrivacy"),
				DefaultValue: "PUBLIC",
				Description:  "Specify whether others should be able to see that the sponsor is sponsoring\nthe sponsorables. Public visibility still does not reveal the dollar value of\nthe sponsorship.",
			},
			"receiveEmails": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Whether the sponsor should receive email updates from the sponsorables.",
			},
			"recurring": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Whether the sponsorships created should continue each billing cycle for the\nsponsor (monthly or annually), versus lasting only a single month. Defaults to\none-time sponsorships.",
			},
			"sponsorLogin": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The username of the user or organization who is acting as the sponsor, paying for the sponsorships.",
			},
			"sponsorships": {
				Type:        graphql.NewNonNull(graphql.NewList(graphql.NewNonNull(r.t("BulkSponsorship")))),
				Description: "The list of maintainers to sponsor and for how much apiece.",
			},
		}
	})
}

func (r *Registry) defineCreateSponsorshipsPayload() {
	r.object("CreateSponsorshipsPayload", "Autogenerated return type of CreateSponsorships.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"sponsorables": {
				Type:        graphql.NewList(graphql.NewNonNull(r.t("Sponsorable"))),
				Description: "The users and organizations who received a sponsorship.",
			},
		}
	})
}

func (r *Registry) defineCreateUserListInput() {
	r.input("CreateUserListInput", "Autogenerated input type of CreateUserList", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"description": {
				Type:        r.t("String"),
				Description: "A description of the list",
			},
			"isPrivate": {
				Type:         r.t("Boolean"),
				DefaultValue: false,
				Description:  "Whether or not the list is private",
			},
			"name": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the new list",
			},
		}
	})
}

func (r *Registry) defineCreateUserListPayload() {
	r.object("CreateUserListPayload", "Autogenerated return type of CreateUserList.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"list": {
				Type:        r.t("UserList"),
				Description: "The list that was just created",
			},
			"viewer": {
				Type:        r.t("User"),
				Description: "The user who created the list",
			},
		}
	})
}

func (r *Registry) defineCreatedCommitContribution() {
	r.object("CreatedCommitContribution", "Represents the contribution a user made by committing to a repository.", []string{"Contribution"}, func() graphql.Fields {
		return graphql.Fields{
			"commitCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "How many commits were made on this day to this repository by the user.",
			},
			"isRestricted": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether this contribution is associated with a record you do not have access to. For\nexample, your own 'first issue' contribution may have been made on a repository you can no\nlonger access.",
			},
			"occurredAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "When this contribution was made.",
			},
			"repository": {
				Type:        graphql.NewNonNull(r.t("Repository")),
				Description: "The repository the user made a commit in.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this contribution.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this contribution.",
			},
			"user": {
				Type:        graphql.NewNonNull(r.t("User")),
				Description: "The user who made this contribution.",
			},
		}
	})
}

func (r *Registry) defineCreatedCommitContributionConnection() {
	r.object("CreatedCommitContributionConnection", "The connection type for CreatedCommitContribution.", nil, func() graphql.Fields {
		return graphql.Fields{
			"edges": {
				Type:        graphql.NewList(r.t("CreatedCommitContributionEdge")),
				Description: "A list of edges.",
			},
			"nodes": {
				Type:        graphql.NewList(r.t("CreatedCommitContribution")),
				Description: "A list of nodes.",
			},
			"pageInfo": {
				Type:        graphql.NewNonNull(r.t("PageInfo")),
				Description: "Information to aid in pagination.",
			},
			"totalCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Identifies the total count of commits across days and repositories in the connection.",
			},
		}
	})
}

func (r *Registry) defineCreatedCommitContributionEdge() {
	r.object("CreatedCommitContributionEdge", "An edge in a connection.", nil, func() graphql.Fields {
		return graphql.Fields{
			"cursor": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A cursor for use in pagination.",
			},
			"node": {
				Type:        r.t("CreatedCommitContribution"),
				Description: "The item at the end of the edge.",
			},
		}
	})
}

func (r *Registry) defineCreatedIssueContribution() {
	r.object("CreatedIssueContribution", "Represents the contribution a user made on GitHub by opening an issue.", []string{"Contribution"}, func() graphql.Fields {
		return graphql.Fields{
			"isRestricted": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether this contribution is associated with a record you do not have access to. For\nexample, your own 'first issue' contribution may have been made on a repository you can no\nlonger access.",
			},
			"issue": {
				Type:        graphql.NewNonNull(r.t("Issue")),
				Description: "The issue that was opened.",
			},
			"occurredAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "When this contribution was made.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this contribution.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this contribution.",
			},
			"user": {
				Type:        graphql.NewNonNull(r.t("User")),
				Description: "The user who made this contribution.",
			},
		}
	})
}

func (r *Registry) defineCreatedIssueContributionConnection() {
	r.object("CreatedIssueContributionConnection", "The connection type for CreatedIssueContribution.", nil, func() graphql.Fields {
		return graphql.Fields{
			"edges": {
				Type:        graphql.NewList(r.t("CreatedIssueContributionEdge")),
				Description: "A list of edges.",
			},
			"nodes": {
				Type:        graphql.NewList(r.t("CreatedIssueContribution")),
				Description: "A list of nodes.",
			},
			"pageInfo": {
				Type:        graphql.NewNonNull(r.t("PageInfo")),
				Description: "Information to aid in pagination.",
			},
			"totalCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Identifies the total count of items in the connection.",
			},
		}
	})
}

func (r *Registry) defineCreatedIssueContributionEdge() {
	r.object("CreatedIssueContributionEdge", "An edge in a connection.", nil, func() graphql.Fields {
		return graphql.Fields{
			"cursor": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A cursor for use in pagination.",
			},
			"node": {
				Type:        r.t("CreatedIssueContribution"),
				Description: "The item at the end of the edge.",
			},
		}
	})
}

func (r *Registry) defineCreatedIssueOrRestrictedContribution() {
	r.union("CreatedIssueOrRestrictedContribution", "Represents either a issue the viewer can access or a restricted contribution.", []string{"CreatedIssueContribution", "RestrictedContribution"})
}

func (r *Registry) defineCreatedPullRequestContribution() {
	r.object("CreatedPullRequestContribution", "Represents the contribution a user made on GitHub by opening a pull request.", []string{"Contribution"}, func() graphql.Fields {
		return graphql.Fields{
			"isRestricted": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether this contribution is associated with a record you do not have access to. For\nexample, your own 'first issue' contribution may have been made on a repository you can no\nlonger access.",
			},
			"occurredAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "When this contribution was made.",
			},
			"pullRequest": {
				Type:        graphql.NewNonNull(r.t("PullRequest")),
				Description: "The pull request that was opened.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this contribution.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this contribution.",
			},
			"user": {
				Type:        graphql.NewNonNull(r.t("User")),
				Description: "The user who made this contribution.",
			},
		}
	})
}

func (r *Registry) defineCreatedPullRequestContributionConnection() {
	r.object("CreatedPullRequestContributionConnection", "The connection type for CreatedPullRequestContribution.", nil, func() graphql.Fields {
		return graphql.Fields{
			"edges": {
				Type:        graphql.NewList(r.t("CreatedPullRequestContributionEdge")),
				Description: "A list of edges.",
			},
			"nodes": {
				Type:        graphql.NewList(r.t("CreatedPullRequestContribution")),
				Description: "A list of nodes.",
			},
			"pageInfo": {
				Type:        graphql.NewNonNull(r.t("PageInfo")),
				Description: "Information to aid in pagination.",
			},
			"totalCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Identifies the total count of items in the connection.",
			},
		}
	})
}

func (r *Registry) defineCreatedPullRequestContributionEdge() {
	r.object("CreatedPullRequestContributionEdge", "An edge in a connection.", nil, func() graphql.Fields {
		return graphql.Fields{
			"cursor": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A cursor for use in pagination.",
			},
			"node": {
				Type:        r.t("CreatedPullRequestContribution"),
				Description: "The item at the end of the edge.",
			},
		}
	})
}

func (r *Registry) defineCreatedPullRequestOrRestrictedContribution() {
	r.union("CreatedPullRequestOrRestrictedContribution", "Represents either a pull request the viewer can access or a restricted contribution.", []string{"CreatedPullRequestContribution", "RestrictedContribution"})
}

func (r *Registry) defineCreatedPullRequestReviewContribution() {
	r.object("CreatedPullRequestReviewContribution", "Represents the contribution a user made by leaving a review on a pull request.", []string{"Contribution"}, func() graphql.Fields {
		return graphql.Fields{
			"isRestricted": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether this contribution is associated with a record you do not have access to. For\nexample, your own 'first issue' contribution may have been made on a repository you can no\nlonger access.",
			},
			"occurredAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "When this contribution was made.",
			},
			"pullRequest": {
				Type:        graphql.NewNonNull(r.t("PullRequest")),
				Description: "The pull request the user reviewed.",
			},
			"pullRequestReview": {
				Type:        graphql.NewNonNull(r.t("PullRequestReview")),
				Description: "The review the user left on the pull request.",
			},
			"repository": {
				Type:        graphql.NewNonNull(r.t("Repository")),
				Description: "The repository containing the pull request that the user reviewed.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this contribution.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this contribution.",
			},
			"user": {
				Type:        graphql.NewNonNull(r.t("User")),
				Description: "The user who made this contribution.",
			},
		}
	})
}

func (r *Registry) defineCreatedPullRequestReviewContributionConnection() {
	r.object("CreatedPullRequestReviewContributionConnection", "The connection type for CreatedPullRequestReviewContribution.", nil, func() graphql.Fields {
		return graphql.Fields{
			"edges": {
				Type:        graphql.NewList(r.t("CreatedPullRequestReviewContributionEdge")),
				Description: "A list of edges.",
			},
			"nodes": {
				Type:        graphql.NewList(r.t("CreatedPullRequestReviewContribution")),
				Description: "A list of nodes.",
			},
			"pageInfo": {
				Type:        graphql.NewNonNull(r.t("PageInfo")),
				Description: "Information to aid in pagination.",
			},
			"totalCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Identifies the total count of items in the connection.",
			},
		}
	})
}

func (r *Registry) defineCreatedPullRequestReviewContributionEdge() {
	r.object("CreatedPullRequestReviewContributionEdge", "An edge in a connection.", nil, func() graphql.Fields {
		return graphql.Fields{
			"cursor": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A cursor for use in pagination.",
			},
			"node": {
				Type:        r.t("CreatedPullRequestReviewContribution"),
				Description: "The item at the end of the edge.",
			},
		}
	})
}

func (r *Registry) defineCreatedRepositoryContribution() {
	r.object("CreatedRepositoryContribution", "Represents the contribution a user made on GitHub by creating a repository.", []string{"Contribution"}, func() graphql.Fields {
		return graphql.Fields{
			"isRestricted": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Whether this contribution is associated with a record you do not have access to. For\nexample, your own 'first issue' contribution may have been made on a repository you can no\nlonger access.",
			},
			"occurredAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "When this contribution was made.",
			},
			"repository": {
				Type:        graphql.NewNonNull(r.t("Repository")),
				Description: "The repository that was created.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this contribution.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this contribution.",
			},
			"user": {
				Type:        graphql.NewNonNull(r.t("User")),
				Description: "The user who made this contribution.",
			},
		}
	})
}

func (r *Registry) defineCreatedRepositoryContributionConnection() {
	r.object("CreatedRepositoryContributionConnection", "The connection type for CreatedRepositoryContribution.", nil, func() graphql.Fields {
		return graphql.Fields{
			"edges": {
				Type:        graphql.NewList(r.t("CreatedRepositoryContributionEdge")),
				Description: "A list of edges.",
			},
			"nodes": {
				Type:        graphql.NewList(r.t("CreatedRepositoryContribution")),
				Description: "A list of nodes.",
			},
			"pageInfo": {
				Type:        graphql.NewNonNull(r.t("PageInfo")),
				Description: "Information to aid in pagination.",
			},
			"totalCount": {
				Type:        graphql.NewNonNull(r.t("Int")),
				Description: "Identifies the total count of items in the connection.",
			},
		}
	})
}

func (r *Registry) defineCreatedRepositoryContributionEdge() {
	r.object("CreatedRepositoryContributionEdge", "An edge in a connection.", nil, func() graphql.Fields {
		return graphql.Fields{
			"cursor": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "A cursor for use in pagination.",
			},
			"node": {
				Type:        r.t("CreatedRepositoryContribution"),
				Description: "The item at the end of the edge.",
			},
		}
	})
}

func (r *Registry) defineCreatedRepositoryOrRestrictedContribution() {
	r.union("CreatedRepositoryOrRestrictedContribution", "Represents either a repository the viewer can access or a restricted contribution.", []string{"CreatedRepositoryContribution", "RestrictedContribution"})
}

func (r *Registry) defineCrossReferencedEvent() {
	r.object("CrossReferencedEvent", "Represents a mention made by one issue or pull request to another.", []string{"Node", "UniformResourceLocatable"}, func() graphql.Fields {
		return graphql.Fields{
			"actor": {
				Type:        r.t("Actor"),
				Description: "Identifies the actor who performed the event.",
			},
			"createdAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "Identifies the date and time when the object was created.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the CrossReferencedEvent object",
			},
			"isCrossRepository": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Reference originated in a different repository.",
			},
			"referencedAt": {
				Type:        graphql.NewNonNull(r.t("DateTime")),
				Description: "Identifies when the reference was made.",
			},
			"resourcePath": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP path for this pull request.",
			},
			"source": {
				Type:        graphql.NewNonNull(r.t("ReferencedSubject")),
				Description: "Issue or pull request that made the reference.",
			},
			"target": {
				Type:        graphql.NewNonNull(r.t("ReferencedSubject")),
				Description: "Issue or pull request to which the reference was made.",
			},
			"url": {
				Type:        graphql.NewNonNull(r.t("URI")),
				Description: "The HTTP URL for this pull request.",
			},
			"willCloseTarget": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Checks if the target will be closed when the source is merged.",
			},
		}
	})
}

func (r *Registry) defineCustomPropertySource() {
	r.union("CustomPropertySource", "Sources which can have custom properties defined.", []string{"Enterprise", "Organization"})
}

func (r *Registry) defineCustomPropertyValue() {
	r.scalar("CustomPropertyValue", "A custom property value can be either a string or an array of strings. All\nproperty types support only a single string value, except for the multi-select\ntype, which supports only a string array.")
}

func (r *Registry) defineCustomPropertyValueInput() {
	r.input("CustomPropertyValueInput", "The custom property name and value to be set.", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"propertyName": {
				Type:        graphql.NewNonNull(r.t("String")),
				Description: "The name of the custom property.",
			},
			"value": {
				Type:        r.t("CustomPropertyValue"),
				Description: "The value to set for the custom property. Using a value of null will unset the\nproperty value, reverting to the default value if the property is required.",
			},
		}
	})
}

func (r *Registry) defineCustomPropertyValueType() {
	r.enum("CustomPropertyValueType", "The allowed value types for a custom property definition.", graphql.EnumValueConfigMap{
		"MULTI_SELECT": {
			Value:       "MULTI_SELECT",
			Description: "A multi-select value.",
		},
		"SINGLE_SELECT": {
			Value:       "SINGLE_SELECT",
			Description: "A single-select value.",
		},
		"STRING": {
			Value:       "STRING",
			Description: "A string value.",
		},
		"TRUE_FALSE": {
			Value:       "TRUE_FALSE",
			Description: "A true/false value.",
		},
		"URL": {
			Value:       "URL",
			Description: "A URL value.",
		},
	})
}

func (r *Registry) defineCvssSeverities() {
	r.object("CvssSeverities", "The Common Vulnerability Scoring System", nil, func() graphql.Fields {
		return graphql.Fields{
			"cvssV3": {
				Type:        r.t("CVSS"),
				Description: "The CVSS v3 severity associated with this advisory",
			},
			"cvssV4": {
				Type:        r.t("CVSS"),
				Description: "The CVSS v4 severity associated with this advisory",
			},
		}
	})
}

func (r *Registry) defineDate() {
	r.scalar("Date", "An ISO-8601 encoded date string.")
}

func (r *Registry) defineDateTime() {
	r.scalar("DateTime", "An ISO-8601 encoded UTC date string.")
}

func (r *Registry) defineDeclineTopicSuggestionInput() {
	r.input("DeclineTopicSuggestionInput", "Autogenerated input type of DeclineTopicSuggestion", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"name": {
				Type:        r.t("String"),
				Description: "The name of the suggested topic.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `name` will be removed.\n**Reason:** Suggested topics are no longer supported",
			},
			"reason": {
				Type:        r.t("TopicSuggestionDeclineReason"),
				Description: "The reason why the suggested topic is declined.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `reason` will be removed.\n**Reason:** Suggested topics are no longer supported",
			},
			"repositoryId": {
				Type:        r.t("ID"),
				Description: "The Node ID of the repository.\n\n**Upcoming Change on 2024-04-01 UTC**\n**Description:** `repositoryId` will be removed.\n**Reason:** Suggested topics are no longer supported",
			},
		}
	})
}

func (r *Registry) defineDeclineTopicSuggestionPayload() {
	r.object("DeclineTopicSuggestionPayload", "Autogenerated return type of DeclineTopicSuggestion.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"topic": {
				Type:              r.t("Topic"),
				Description:       "The declined topic.",
				DeprecationReason: "Suggested topics are no longer supported Removal on 2024-04-01 UTC.",
			},
		}
	})
}

func (r *Registry) defineDefaultRepositoryPermissionField() {
	r.enum("DefaultRepositoryPermissionField", "The possible base permissions for repositories.", graphql.EnumValueConfigMap{
		"ADMIN": {
			Value:       "ADMIN",
			Description: "Can read, write, and administrate repos by default",
		},
		"NONE": {
			Value:       "NONE",
			Description: "No access",
		},
		"READ": {
			Value:       "READ",
			Description: "Can read repos by default",
		},
		"WRITE": {
			Value:       "WRITE",
			Description: "Can read and write repos by default",
		},
	})
}

func (r *Registry) defineDeletable() {
	r.interfaceType("Deletable", "Entities that can be deleted.", func() graphql.Fields {
		return graphql.Fields{
			"viewerCanDelete": {
				Type:        graphql.NewNonNull(r.t("Boolean")),
				Description: "Check if the current viewer can delete this object.",
			},
		}
	})
}

func (r *Registry) defineDeleteBranchProtectionRuleInput() {
	r.input("DeleteBranchProtectionRuleInput", "Autogenerated input type of DeleteBranchProtectionRule", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"branchProtectionRuleId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The global relay id of the branch protection rule to be deleted.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteBranchProtectionRulePayload() {
	r.object("DeleteBranchProtectionRulePayload", "Autogenerated return type of DeleteBranchProtectionRule.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteDeploymentInput() {
	r.input("DeleteDeploymentInput", "Autogenerated input type of DeleteDeployment", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the deployment to be deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteDeploymentPayload() {
	r.object("DeleteDeploymentPayload", "Autogenerated return type of DeleteDeployment.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteDiscussionCommentInput() {
	r.input("DeleteDiscussionCommentInput", "Autogenerated input type of DeleteDiscussionComment", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node id of the discussion comment to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteDiscussionCommentPayload() {
	r.object("DeleteDiscussionCommentPayload", "Autogenerated return type of DeleteDiscussionComment.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"comment": {
				Type:        r.t("DiscussionComment"),
				Description: "The discussion comment that was just deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteDiscussionInput() {
	r.input("DeleteDiscussionInput", "Autogenerated input type of DeleteDiscussion", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The id of the discussion to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteDiscussionPayload() {
	r.object("DeleteDiscussionPayload", "Autogenerated return type of DeleteDiscussion.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"discussion": {
				Type:        r.t("Discussion"),
				Description: "The discussion that was just deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteEnvironmentInput() {
	r.input("DeleteEnvironmentInput", "Autogenerated input type of DeleteEnvironment", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the environment to be deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteEnvironmentPayload() {
	r.object("DeleteEnvironmentPayload", "Autogenerated return type of DeleteEnvironment.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteIpAllowListEntryInput() {
	r.input("DeleteIpAllowListEntryInput", "Autogenerated input type of DeleteIpAllowListEntry", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"ipAllowListEntryId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the IP allow list entry to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteIpAllowListEntryPayload() {
	r.object("DeleteIpAllowListEntryPayload", "Autogenerated return type of DeleteIpAllowListEntry.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"ipAllowListEntry": {
				Type:        r.t("IpAllowListEntry"),
				Description: "The IP allow list entry that was deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueCommentInput() {
	r.input("DeleteIssueCommentInput", "Autogenerated input type of DeleteIssueComment", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the comment to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueCommentPayload() {
	r.object("DeleteIssueCommentPayload", "Autogenerated return type of DeleteIssueComment.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueFieldInput() {
	r.input("DeleteIssueFieldInput", "Autogenerated input type of DeleteIssueField", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"fieldId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the field to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueFieldPayload() {
	r.object("DeleteIssueFieldPayload", "Autogenerated return type of DeleteIssueField.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueField": {
				Type:        r.t("IssueFields"),
				Description: "The deleted issue field.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueFieldValueInput() {
	r.input("DeleteIssueFieldValueInput", "Autogenerated input type of DeleteIssueFieldValue", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"fieldId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the field to delete.",
			},
			"issueId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the issue.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueFieldValuePayload() {
	r.object("DeleteIssueFieldValuePayload", "Autogenerated return type of DeleteIssueFieldValue.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issue": {
				Type:        r.t("Issue"),
				Description: "The issue object.",
			},
			"success": {
				Type:        r.t("Boolean"),
				Description: "Whether the field value was successfully deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueInput() {
	r.input("DeleteIssueInput", "Autogenerated input type of DeleteIssue", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the issue to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteIssuePayload() {
	r.object("DeleteIssuePayload", "Autogenerated return type of DeleteIssue.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"repository": {
				Type:        r.t("Repository"),
				Description: "The repository the issue belonged to",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueTypeInput() {
	r.input("DeleteIssueTypeInput", "Autogenerated input type of DeleteIssueType", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issueTypeId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the issue type to delete",
			},
		}
	})
}

func (r *Registry) defineDeleteIssueTypePayload() {
	r.object("DeleteIssueTypePayload", "Autogenerated return type of DeleteIssueType.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"deletedIssueTypeId": {
				Type:        r.t("ID"),
				Description: "The ID of the deleted issue type",
			},
		}
	})
}

func (r *Registry) defineDeleteLabelInput() {
	r.input("DeleteLabelInput", "Autogenerated input type of DeleteLabel", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"id": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Node ID of the label to be deleted.",
			},
		}
	})
}

func (r *Registry) defineDeleteLabelPayload() {
	r.object("DeleteLabelPayload", "Autogenerated return type of DeleteLabel.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteLinkedBranchInput() {
	r.input("DeleteLinkedBranchInput", "Autogenerated input type of DeleteLinkedBranch", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"linkedBranchId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the linked branch",
			},
		}
	})
}

func (r *Registry) defineDeleteLinkedBranchPayload() {
	r.object("DeleteLinkedBranchPayload", "Autogenerated return type of DeleteLinkedBranch.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"issue": {
				Type:        r.t("Issue"),
				Description: "The issue the linked branch was unlinked from.",
			},
		}
	})
}

func (r *Registry) defineDeletePackageVersionInput() {
	r.input("DeletePackageVersionInput", "Autogenerated input type of DeletePackageVersion", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"packageVersionId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the package version to be deleted.",
			},
		}
	})
}

func (r *Registry) defineDeletePackageVersionPayload() {
	r.object("DeletePackageVersionPayload", "Autogenerated return type of DeletePackageVersion.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"success": {
				Type:        r.t("Boolean"),
				Description: "Whether or not the operation succeeded.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectCardInput() {
	r.input("DeleteProjectCardInput", "Autogenerated input type of DeleteProjectCard", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"cardId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The id of the card to delete.",
			},
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectCardPayload() {
	r.object("DeleteProjectCardPayload", "Autogenerated return type of DeleteProjectCard.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"column": {
				Type:        r.t("ProjectColumn"),
				Description: "The column the deleted card was in.",
			},
			"deletedCardId": {
				Type:        r.t("ID"),
				Description: "The deleted card ID.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectColumnInput() {
	r.input("DeleteProjectColumnInput", "Autogenerated input type of DeleteProjectColumn", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"columnId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The id of the column to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectColumnPayload() {
	r.object("DeleteProjectColumnPayload", "Autogenerated return type of DeleteProjectColumn.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"deletedColumnId": {
				Type:        r.t("ID"),
				Description: "The deleted column ID.",
			},
			"project": {
				Type:        r.t("Project"),
				Description: "The project the deleted column was in.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectInput() {
	r.input("DeleteProjectInput", "Autogenerated input type of DeleteProject", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The Project ID to update.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectPayload() {
	r.object("DeleteProjectPayload", "Autogenerated return type of DeleteProject.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"owner": {
				Type:        r.t("ProjectOwner"),
				Description: "The repository or organization the project was removed from.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2FieldInput() {
	r.input("DeleteProjectV2FieldInput", "Autogenerated input type of DeleteProjectV2Field", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"fieldId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the field to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2FieldPayload() {
	r.object("DeleteProjectV2FieldPayload", "Autogenerated return type of DeleteProjectV2Field.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectV2Field": {
				Type:        r.t("ProjectV2FieldConfiguration"),
				Description: "The deleted field.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2Input() {
	r.input("DeleteProjectV2Input", "Autogenerated input type of DeleteProjectV2", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the Project to delete.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2ItemInput() {
	r.input("DeleteProjectV2ItemInput", "Autogenerated input type of DeleteProjectV2Item", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"itemId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the item to be removed.",
			},
			"projectId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the Project from which the item should be removed.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2ItemPayload() {
	r.object("DeleteProjectV2ItemPayload", "Autogenerated return type of DeleteProjectV2Item.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"deletedItemId": {
				Type:        r.t("ID"),
				Description: "The ID of the deleted item.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2Payload() {
	r.object("DeleteProjectV2Payload", "Autogenerated return type of DeleteProjectV2.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"projectV2": {
				Type:        r.t("ProjectV2"),
				Description: "The deleted Project.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2StatusUpdateInput() {
	r.input("DeleteProjectV2StatusUpdateInput", "Autogenerated input type of DeleteProjectV2StatusUpdate", func() graphql.InputObjectConfigFieldMap {
		return graphql.InputObjectConfigFieldMap{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"statusUpdateId": {
				Type:        graphql.NewNonNull(r.t("ID")),
				Description: "The ID of the status update to be removed.",
			},
		}
	})
}

func (r *Registry) defineDeleteProjectV2StatusUpdatePayload() {
	r.object("DeleteProjectV2StatusUpdatePayload", "Autogenerated return type of DeleteProjectV2StatusUpdate.", nil, func() graphql.Fields {
		return graphql.Fields{
			"clientMutationId": {
				Type:        r.t("String"),
				Description: "A unique identifier for the client performing the mutation.",
			},
			"deletedStatusUpdateId": {
				Type:        r.t("ID"),
				Description: "The ID of the deleted status update.",
			},
			"projectV2": {
				Type:        r.t("ProjectV2"),
				Description: "The project the deleted status update was in.",
			},
		}
	})
}
